ci:
  autoupdate_schedule: monthly

default_language_version:
  node: 24.11.1

default_stages:
  - pre-commit
exclude: >
  (?x)^(
    ^(\/|)vendor\/(.*?)$|
    .+\.node_modules\/.*$|
    .+\.external_modules.*$|
    .+\.terraform.*$|
    pnpm-lock.yaml|
    .+\.venv.*$|
    .+\.lock$|
    .+\.mdx$|
  )$

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words=.ci/linters/.codespell-ignores
        exclude: >
          (?x)^(
            AGENTS.md|
            app/components/sections\/.*$|
            app/data\/.*$|
            app/ia/datasets\/.*$|
            app/routes\/.*$|
            CHANGELOG.md|
            go.mod|
            go.sum|
            openapi.yaml|
            .+\.lock$|
            .+\.mdx$|
            .+\.node_modules\/.*$|
            .+\.sops.*$|
            .+\.vendor\/.*$|
          )$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@hadenlabs/commitlint-config"]
        args:
          - --config=.ci/linters/.commitlintrc.json
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
        files: ^(?!\.?git-crypt)
        exclude: >
          (?x)^(
            .+\.gitleaks.toml$|
            test/fixtures/keys/.*-test.*$
          )$
      - id: check-merge-conflict
      - id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
      - id: check-case-conflict
      - id: check-json
        exclude: >
          (?x)^(
            .zed/tasks.json$|
          )$
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: sort-simple-yaml

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        args:
          - --config=.ci/linters/markdown-link-config.json
        exclude: >
          (?x)^(
            .+\.docs/env-vars.md$|
            docs/env-vars.md$|
            docs\/include\/terraform.md$|
            .+\.tpl.md$|
          )$

  - repo: https://github.com/hadenlabs/pre-commit-hooks
    rev: 0.6.0
    hooks:
      - id: do-not-commit
      - id: shellcheck
        exclude: >
          (?x)^(
            .+\.provision/git/hooks/prepare-commit-msg$|
            .+\.tpl.sh$|
          )$
        args:
          - --exclude=SC1072,SC1073,SC2068
      - id: gitleaks
        args:
          - --path=.
          - --repo-config-path=.ci/linters/.gitleaks.toml
          - --verbose
      - id: hadolint
        args:
          - --config=.ci/linters/.hadolint.yaml
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
